// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb-LMK_2aCp3V9zN0KFfqwUF21ut8jfro',
    appId: '1:853815335756:web:a275a8832748169778cde9',
    messagingSenderId: '853815335756',
    projectId: 'ensiconnect',
    authDomain: 'ensiconnect.firebaseapp.com',
    storageBucket: 'ensiconnect.firebasestorage.app',
    measurementId: 'G-6T7BRHEY5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCweMOLcXtcYxFCA2pxmfQJ0ff--qG9jJo',
    appId: '1:853815335756:android:a4a61a79b1a5d1f478cde9',
    messagingSenderId: '853815335756',
    projectId: 'ensiconnect',
    storageBucket: 'ensiconnect.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb-LMK_2aCp3V9zN0KFfqwUF21ut8jfro',
    appId: '1:853815335756:web:73f8fc4caac592b378cde9',
    messagingSenderId: '853815335756',
    projectId: 'ensiconnect',
    authDomain: 'ensiconnect.firebaseapp.com',
    storageBucket: 'ensiconnect.firebasestorage.app',
    measurementId: 'G-02THE1Y9EY',
  );
}
